version: '3.5'
services:
    web:
        environment:
            - "DB_HOSTNAME=db"
            - "SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-default}"
        container_name: dcsa_bkg
        build:
            .
        ports:
            - 9090:9090
        logging:
            options:
                max-file: '10'
                max-size: 200k

    dcsa-test-db:
        container_name: dcsa_db
        environment:
            POSTGRES_PASSWORD: "change_this_password"
        build:
            DCSA-Information-Model/datamodel/
        ports:
            - 5432:5432
